name: Publish to crates.io and draft release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.89.0
      - run: |
          cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  build:
    name: Build ${{ matrix.os }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
    env:
      RUSTFLAGS: -C target-cpu=native
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install X11 libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libx11-xcb-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
      - name: Build
        run: |
          cargo build --release
      - name: Archive
        id: archive
        run: |
          BIN=${{ github.event.repository.name }}          # <‑‑ change if binary name differs
          ARTIFACT="target/release/${BIN}"
          TARGET=`rustc -vV | awk '/^host/ { print $2 }'`
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ARTIFACT="${ARTIFACT}.exe"
          fi
          mkdir -p dist
          cp "$ARTIFACT" dist/
          echo "target=${TARGET}" >> "$GITHUB_OUTPUT"

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a -tzip dist/${BIN}-${TARGET}.zip dist/*
            echo "artifact=${BIN}-${TARGET}.zip" >> "$GITHUB_OUTPUT"
          else
            tar czf dist/${BIN}-${TARGET}.tar.gz -C dist .
            echo "artifact=${BIN}-${TARGET}.tar.gz" >> "$GITHUB_OUTPUT"
          fi

      # -------------------------------------------------------------
      # Upload the archive as a job artifact for the release step
      # -------------------------------------------------------------
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.target }}
          path: dist/${{ steps.archive.outputs.artifact }}
          retention-days: 1   # keep it only for the next job
  release:
    name: Release on GitHub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}